### ISSUE TITLE
description support

### ISSUE THREAD

**Issue by matthewmueller** [ForbesLindesay/graphql-schema-gen#2]
Support for descriptions would be nice. I was thinking something like:

```
type User {
  $id: Int - Mongo ID
  name: String - Name of the user
  uid: String - User's unique identifier
}
```

**Comment by ForbesLindesay** [comment]
Possibly should be better documented, but we already support descriptions via a comment above the field.

**Comment by matthewmueller** [comment]
ahh okay cool. that works, thanks!
